export const productsData = [
  {
    product_name: "Ngưu Chương Chi (2 boxes)",
    product_code: "001",
    price: 520,
    quantity: 2,
    currency_unit: "NVD",
    currency_value: 17500000,
    exchange_unit: "USD",
    exchange_value: 470,
    slug: "nguu-chuong-chi-2-boxes",
  },
  {
    product_name: "Hồng Sâm Cao Cấp (3 boxes)",
    product_code: "003",
    price: 600,
    quantity: 1,
    currency_unit: "NVD",
    currency_value: 19200000,
    exchange_unit: "USD",
    exchange_value: 510,
    slug: "hong-sam-cao-cap-3-boxes",
  },
  {
    product_name: "Linh Chi Đỏ Hàn Quốc (5 boxes)",
    product_code: "004",
    price: 580,
    quantity: 3,
    currency_unit: "NVD",
    currency_value: 18850000,
    exchange_unit: "USD",
    exchange_value: 495,
    slug: "linh-chi-do-han-quoc-5-boxes",
  },
  {
    product_name: "Nhân Sâm Đặc Biệt (2 boxes)",
    product_code: "005",
    price: 540,
    quantity: 2,
    currency_unit: "NVD",
    currency_value: 18250000,
    exchange_unit: "USD",
    exchange_value: 485,
    slug: "nhan-sam-dac-biet-1-box",
  },
];
